### ISSUE TITLE
Error building against musl

### ISSUE THREAD

**Issue by andrewrynhard** [foniod/redbpf#130]
I couldn't find a great example on how to compile against `musl`. Using archlinux (after installing `musl` and the build deps) I am seeing:

```
...
  TARGET = Some("x86_64-unknown-linux-musl")
  OPT_LEVEL = Some("z")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_x86_64-unknown-linux-musl = None
  CC_x86_64_unknown_linux_musl = None
  TARGET_CC = None
  CC = None
  CROSS_COMPILE = None
  CFLAGS_x86_64-unknown-linux-musl = None
  CFLAGS_x86_64_unknown_linux_musl = None
  TARGET_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
...
  running: "musl-gcc" "-Os" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "libbpf/include/uapi" "-I" "libbpf/include" "-I" "bcc" "-I" "libelf" "-I" "." "-I" "/usr/lib/modules/5.11.8-arch1-1/build/arch/x86/include/generated/uapi" "-I" "/usr/lib/modules/5.11.8-arch1-1/build/arch/x86/include/uapi" "-I" "/usr/lib/modules/5.11.8-arch1-1/build/arch/x86/include/" "-I" "/usr/lib/modules/5.11.8-arch1-1/build/include/generated/uapi" "-I" "/usr/lib/modules/5.11.8-arch1-1/build/include/uapi" "-I" "/usr/lib/modules/5.11.8-arch1-1/build/include" "-Wall" "-Wextra" "-Wno-sign-compare" "-Wno-int-conversion" "-Wno-unused-parameter" "-Wno-unused-result" "-Wno-format-truncation" "-Wno-missing-field-initializers" "-include" "bpfsys-musl.h" "-include" "linux/stddef.h" "-DCOMPAT_NEED_REALLOCARRAY=1" "-o" "/usr/local/target/x86_64-unknown-linux-musl/release/build/bpf-sys-08ba1431d87e1df6/out/libbpf/src/libbpf.o" "-c" "libbpf/src/libbpf.c"
  cargo:warning=In file included from libbpf/src/libbpf.c:44:
  cargo:warning=libbpf/include/tools/libc_compat.h:11:21: error: static declaration of ‘reallocarray’ follows non-static declaration
  cargo:warning=   11 | static inline void *reallocarray(void *ptr, size_t nmemb, size_t size)
  cargo:warning=      |                     ^~~~~~~~~~~~
  cargo:warning=In file included from libbpf/src/libbpf.c:16:
  cargo:warning=/usr/lib/musl/include/stdlib.h:148:7: note: previous declaration of ‘reallocarray’ was here
  cargo:warning=  148 | void *reallocarray (void *, size_t, size_t);
  cargo:warning=      |       ^~~~~~~~~~~~
  exit code: 1

  --- stderr


  error occurred: Command "musl-gcc" "-Os" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "libbpf/include/uapi" "-I" "libbpf/include" "-I" "bcc" "-I" "libelf" "-I" "." "-I" "/usr/lib/modules/5.11.8-arch1-1/build/arch/x86/include/generated/uapi" "-I" "/usr/lib/modules/5.11.8-arch1-1/build/arch/x86/include/uapi" "-I" "/usr/lib/modules/5.11.8-arch1-1/build/arch/x86/include/" "-I" "/usr/lib/modules/5.11.8-arch1-1/build/include/generated/uapi" "-I" "/usr/lib/modules/5.11.8-arch1-1/build/include/uapi" "-I" "/usr/lib/modules/5.11.8-arch1-1/build/include" "-Wall" "-Wextra" "-Wno-sign-compare" "-Wno-int-conversion" "-Wno-unused-parameter" "-Wno-unused-result" "-Wno-format-truncation" "-Wno-missing-field-initializers" "-include" "bpfsys-musl.h" "-include" "linux/stddef.h" "-DCOMPAT_NEED_REALLOCARRAY=1" "-o" "/usr/local/target/x86_64-unknown-linux-musl/release/build/bpf-sys-08ba1431d87e1df6/out/libbpf/src/libbpf.o" "-c" "libbpf/src/libbpf.c" with args "musl-gcc" did not execute successfully (status code exit code: 1).
```

**Comment by andrewrynhard** [comment]
I managed to get this working with Ubuntu. Took a peak at the Ingraind project: https://github.com/andrewrynhard/cosi-demo/blob/initial-implementation/Dockerfile#L8-L20. I would prefer to avoid Ubuntu if I can. In fact, I plan to use `redbpf` in [Talos](https://github.com/talos-systems/talos) where we maintain our own C toolchain based on `musl`. I'd like to understand this a bit before I go and and LLVM and Clang to our toolchain.

**Comment by rhdxmr** [comment]
It seems that the error is related to libbpf (https://github.com/libbpf/libbpf).
There might exist problems about building libbpf under less common environment.
Or the problem might be fixed in the recent version of libbpf..
But I am not sure because I had no experience of building redbpf using musl yet.

cc. @rsdy

**Comment by rsdy** [comment]
@andrewrynhard Can you send me the full command you're using to build with `musl-gcc` in Arch? I want to reproduce this before getting to any conclusions. I vaguely remember that the Ubuntu `musl-gcc` package is specifically _not_ intended to be relied on to compile complex pieces of software, and I don't know if the same is true for Arch.

**Comment by rsdy** [comment]
Ok, just did a quick test, and `cargo +stable build --release --target=x86_64-unknown-linux-musl` produces the same result. I tried pulling in a new `libbpf` version, but now I get
```
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running: "musl-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "libbpf/include/uapi" "-I" "libbpf/include" "-I" "bcc" "-I" "libelf" "-I" "." "-I" "/lib/modules/5.10.23-1-lts/build/arch/x86/include/generated/uapi" "-I" "/lib/modules/5.10.23-1-lts/build/arch/x86/include/uapi" "-I" "/lib/modules/5.10.23-1-lts/build/arch/x86/include/" "-I" "/lib/modules/5.10.23-1-lts/build/include/generated/uapi" "-I" "/lib/modules/5.10.23-1-lts/build/include/uapi" "-I" "/lib/modules/5.10.23-1-lts/build/include" "-Wall" "-Wextra" "-Wno-sign-compare" "-Wno-int-conversion" "-Wno-unused-parameter" "-Wno-unused-result" "-Wno-format-truncation" "-Wno-missing-field-initializers" "-include" "bpfsys-musl.h" "-include" "linux/stddef.h" "-DCOMPAT_NEED_REALLOCARRAY=1" "-o" "/home/p2501/rust/redbpf/target/x86_64-unknown-linux-musl/release/build/bpf-sys-4afc5465d18a986f/out/libbpf/src/bpf.o" "-c" "libbpf/src/bpf.c"
  exit code: 0
  running: "musl-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "libbpf/include/uapi" "-I" "libbpf/include" "-I" "bcc" "-I" "libelf" "-I" "." "-I" "/lib/modules/5.10.23-1-lts/build/arch/x86/include/generated/uapi" "-I" "/lib/modules/5.10.23-1-lts/build/arch/x86/include/uapi" "-I" "/lib/modules/5.10.23-1-lts/build/arch/x86/include/" "-I" "/lib/modules/5.10.23-1-lts/build/include/generated/uapi" "-I" "/lib/modules/5.10.23-1-lts/build/include/uapi" "-I" "/lib/modules/5.10.23-1-lts/build/include" "-Wall" "-Wextra" "-Wno-sign-compare" "-Wno-int-conversion" "-Wno-unused-parameter" "-Wno-unused-result" "-Wno-format-truncation" "-Wno-missing-field-initializers" "-include" "bpfsys-musl.h" "-include" "linux/stddef.h" "-DCOMPAT_NEED_REALLOCARRAY=1" "-o" "/home/p2501/rust/redbpf/target/x86_64-unknown-linux-musl/release/build/bpf-sys-4afc5465d18a986f/out/libbpf/src/bpf_prog_linfo.o" "-c" "libbpf/src/bpf_prog_linfo.c"
  exit code: 0
  running: "musl-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "libbpf/include/uapi" "-I" "libbpf/include" "-I" "bcc" "-I" "libelf" "-I" "." "-I" "/lib/modules/5.10.23-1-lts/build/arch/x86/include/generated/uapi" "-I" "/lib/modules/5.10.23-1-lts/build/arch/x86/include/uapi" "-I" "/lib/modules/5.10.23-1-lts/build/arch/x86/include/" "-I" "/lib/modules/5.10.23-1-lts/build/include/generated/uapi" "-I" "/lib/modules/5.10.23-1-lts/build/include/uapi" "-I" "/lib/modules/5.10.23-1-lts/build/include" "-Wall" "-Wextra" "-Wno-sign-compare" "-Wno-int-conversion" "-Wno-unused-parameter" "-Wno-unused-result" "-Wno-format-truncation" "-Wno-missing-field-initializers" "-include" "bpfsys-musl.h" "-include" "linux/stddef.h" "-DCOMPAT_NEED_REALLOCARRAY=1" "-o" "/home/p2501/rust/redbpf/target/x86_64-unknown-linux-musl/release/build/bpf-sys-4afc5465d18a986f/out/libbpf/src/btf.o" "-c" "libbpf/src/btf.c"
  exit code: 0
  running: "musl-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "libbpf/include/uapi" "-I" "libbpf/include" "-I" "bcc" "-I" "libelf" "-I" "." "-I" "/lib/modules/5.10.23-1-lts/build/arch/x86/include/generated/uapi" "-I" "/lib/modules/5.10.23-1-lts/build/arch/x86/include/uapi" "-I" "/lib/modules/5.10.23-1-lts/build/arch/x86/include/" "-I" "/lib/modules/5.10.23-1-lts/build/include/generated/uapi" "-I" "/lib/modules/5.10.23-1-lts/build/include/uapi" "-I" "/lib/modules/5.10.23-1-lts/build/include" "-Wall" "-Wextra" "-Wno-sign-compare" "-Wno-int-conversion" "-Wno-unused-parameter" "-Wno-unused-result" "-Wno-format-truncation" "-Wno-missing-field-initializers" "-include" "bpfsys-musl.h" "-include" "linux/stddef.h" "-DCOMPAT_NEED_REALLOCARRAY=1" "-o" "/home/p2501/rust/redbpf/target/x86_64-unknown-linux-musl/release/build/bpf-sys-4afc5465d18a986f/out/libbpf/src/libbpf.o" "-c" "libbpf/src/libbpf.c"
  cargo:warning=In file included from libbpf/src/libbpf.c:35:
  cargo:warning=/lib/modules/5.10.23-1-lts/build/include/uapi/linux/limits.h:7: warning: "NGROUPS_MAX" redefined
  cargo:warning=    7 | #define NGROUPS_MAX    65536 /* supplemental group IDs are available */
  cargo:warning=      |
  cargo:warning=In file included from libbpf/src/libbpf.c:21:
  cargo:warning=/usr/lib/musl/include/limits.h:48: note: this is the location of the previous definition
  cargo:warning=   48 | #define NGROUPS_MAX 32
  cargo:warning=      |
  cargo:warning=libbpf/src/libbpf.c:49:10: fatal error: zlib.h: No such file or directory
  cargo:warning=   49 | #include <zlib.h>
  cargo:warning=      |          ^~~~~~~~
  cargo:warning=compilation terminated.
```

So I will need to fix the build env before continuing on this road.

**Comment by andrewrynhard** [comment]
@rsdy I have since moved on to Ubuntu, but let me put together a `Dockerfile`. I will send once I have it.

**Comment by pcolazurdo** [comment]
I recently ran through a series of issues when trying to build with Ubuntu 18.04. - More info at: https://github.com/redsift/ingraind-build/issues/2
After fixing this as documented on the issue, I've struggled to build as I was receiving a few different type of errors: 
* Unable to build if no target is defined, producing errors:   
``` 
Compiling ingraind v1.0.0 (/local)
error: linking with `cc` failed: exit code: 1
...
  = note: /usr/bin/ld: /tmp/rustchLm9DQ/libopenssl_sys-4c5a9937b56b542c.rlib(s23_meth.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE
object; recompile with -fPIC
          /usr/bin/ld: /tmp/rustchLm9DQ/libopenssl_sys-4c5a9937b56b542c.rlib(s23_srvr.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE
object; recompile with -fPIC
          /usr/bin/ld: /tmp/rustchLm9DQ/libopenssl_sys-4c5a9937b56b542c.rlib(s23_clnt.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making
 a PIE object; recompile with -fPIC
          /usr/bin/ld: /tmp/rustchLm9DQ/libopenssl_sys-4c5a9937b56b542c.rlib(s23_lib.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making
a PIE object; recompile with -fPIC
...
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
error: aborting due to previous error
error: could not compile `ingraind`
To learn more, run the command again with --verbose.
```
The only solution was to use ```--target=x86_64-unknown-linux-musl``` which got me to the next error:

* ```--target=x86_64-unknown-linux-musl``` fails due to  
```
error: failed to run custom build command for `redbpf-probes v1.3.0`

Caused by:
  process didn't exit successfully: `/local/target/release/build/redbpf-probes-95c2ccc3902c6de8/build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=include/
  cargo:rerun-if-changed=include/bpf_helper_defs.h
  cargo:rerun-if-changed=include/bpf_helpers.h
  cargo:rerun-if-changed=include/redbpf_helpers.h
  cargo:rerun-if-changed=include/xdp.h

  --- stderr
  /usr/src/linux-headers-4.15.0-142-generic/include/linux/kernel.h:6:10: fatal error: 'stdarg.h' file not found
  /usr/src/linux-headers-4.15.0-142-generic/include/linux/kernel.h:6:10: fatal error: 'stdarg.h' file not found, err: true
  thread 'main' panicked at 'failed to generate bindings: ()', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/redbpf-probes-1.3.0/build.rs:84:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```
   The solution for this is to set the INCLUDE_PATH before running ```cargo buld``` like this:
```
export C_INCLUDE_PATH=/usr/include/x86_64-linux-musl/
export CPLUS_INCLUDE_PATH=/usr/include/x86_64-linux-musl/
```

With this, ```ingraind``` compiles and works fine, in a few targets, including Amazon Linux 2

**Comment by rsdy** [comment]
@pcolazurdo Thanks for this. I won't have much time to focus on clearing up the build system, but will definitely keep this in mind in a few weeks when I get around to it.
